# CS231a PSET 1

You can use this Jupyter/Colab notebook to write your code in, which could save you the trouble of having to set up Python or installing packages.

# [Optional] Colab Preparation
First, we need to be able to access the data for this problem. Run the following:

In [2]:
import os

FOLDERNAME="E:\course\cs231a\ps1"

# enter the foldername in your Drive where you have saved the unzipped
# the files containing the '.npy' files needed for problem 2
# e.g. '/content/drive/MyDrive/cs231a'


assert FOLDERNAME is not None, "[!] Enter the foldername."
os.chdir(FOLDERNAME)

print('Files in this folder:')
print(os.listdir('.'))

Files in this folder:
['.ipynb_checkpoints', 'back_image.npy', 'front.png', 'front_image.npy', 'p2.py', 'p3.py', 'PSET1.ipynb', 'real_XY.npy', 'utils.py', '__pycache__']


Also import the problem functions with autoreload:

In [3]:
%load_ext autoreload
%autoreload 2

from p2 import compute_camera_matrix, rms_error, test_p2
from p3 import (
    compute_vanishing_point,
    compute_K_from_vanishing_points,
    compute_angle_between_planes,
    compute_rotation_matrix_between_cameras,
    test_p3,
)

# Problem 2: Affine Camera Calibration
Now, you can fill out the logic for this problem. Please go to `p2.py` and fill out the following functions:
- `compute_camera_matrix`
- `rms_error`

Once done, you can run the follow code to test your implementation. `p2.py` will be submitted to Gradescope.

In [4]:
# Test code for CS231A Homework 1, Problem 2
test_p2()

Camera Matrix:
 [[ 5.31276507e-01 -1.80886074e-02  1.20509667e-01  1.29720641e+02]
 [ 4.84975447e-02  5.36366401e-01 -1.02675222e-01  4.43879607e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

RMS Error:  0.993830483279844


e:\course\cs231a\ps1\p2.py:45: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  M1=np.linalg.lstsq(Pi,p)[0].T


# Problem 3: Single View Geometry

First, make sure you have already run the code block for having access to image files from Problem 2. Next, please go to `p3.py` and fill out the following functions:
- `compute_vanishing_point`
- `compute_K_from_vanishing_points`
- `compute_angle_between_planes`
- `compute_rotation_matrix_between_cameras`

Once done, you can run the follow code to test your implementation. `p3.py` will be submitted to Gradescope.

In [20]:
# Test code for CS231A Homework 1, Problem 3
test_p3()

Intrinsic Matrix:
 [[2.36901605e+03 0.00000000e+00 1.37945684e+03]
 [0.00000000e+00 2.36901605e+03 9.63015492e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]

Actual Matrix:
 [[2.448e+03 0.000e+00 1.253e+03]
 [0.000e+00 2.438e+03 9.860e+02]
 [0.000e+00 0.000e+00 1.000e+00]]

Angle between floor and box: 89.81938858899669
Rotation between two cameras:
 [[ 1.05220283 -0.06187726  0.06406076]
 [ 0.02418414  1.0221037  -0.03169809]
 [-0.09924512  0.0105692   0.91794226]]

Angle around z-axis (pointing out of camera): 3.365537 degrees
Angle around y-axis (pointing vertically): 3.989678 degrees
Angle around x-axis (pointing horizontally): 1.977734 degrees


e:\course\cs231a\ps1\p3.py:106: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  R=np.linalg.lstsq(direction1,direction2)[0].T


That's it, you are done! Remember to submit your code to Gradescope by zipping the `.py` files and uploading the zip file to the coding assignment.

